### ISSUE TITLE
Message error w single node

### ISSUE THREAD

**Issue by uhuruhashimoto** [ajmcquilkin/meshtastic-emergency-response-client#229] opened 2023-01-26 15:28 UTC
Repro: 
Run `pnpm run rust:dev` and connect an uninitialized node through serial. Click on messages. 

Error message: 
![Screen Shot 2023-01-26 at 10.22.26 AM.png](https://images.zenhubusercontent.com/6348d56e9a9fbc06582530e5/790d720f-6fc3-40fa-88df-e575adb629da)

**Comment by ajmcquilkin** [comment] 2023-02-08 16:24
Duplicate of #213

**Closed by ajmcquilkin** 2023-02-08 16:24 UTC
Labels: bug
